[2025-04-30 12:31:02,087] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
04/30 [12:31:11] INFO     | >> [*] Prismatic VLM Training :: Gathering Light                                                                                   pretrain.py:122
                 INFO     | >>     |=> "Life is like a prism; what you see depends on how you turn the glass."                                                 pretrain.py:136
Traceback (most recent call last):
  File "/home/user1/arash_prism_training/prismatic-vlms/scripts/pretrain.py", line 252, in <module>
    pretrain()
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/argparsing.py", line 228, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/home/user1/arash_prism_training/prismatic-vlms/scripts/pretrain.py", line 143, in pretrain
    draccus.dump(cfg, open(run_dir / "config.yaml", "w"))
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/cfgparsing.py", line 134, in dump
    config_dict = encode(config)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/registry_utils.py", line 78, in wrapper
    return base_func(*args, **kw)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 118, in encode
    raise e
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 111, in encode
    return encode_dataclass(obj, declared_type)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 142, in encode_dataclass
    d[field.name] = encode(value, field_type)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/registry_utils.py", line 78, in wrapper
    return base_func(*args, **kw)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 118, in encode
    raise e
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 109, in encode
    return encode_choice(obj, underlying_type)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 159, in encode_choice
    encoded = encode_dataclass(obj, declared_type)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 142, in encode_dataclass
    d[field.name] = encode(value, field_type)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/registry_utils.py", line 78, in wrapper
    return base_func(*args, **kw)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 100, in encode
    return fn(obj, declared_type)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 225, in encode_tuple
    return [encode(x, t) for x, t in zip(obj, type_args)]
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 225, in <listcomp>
    return [encode(x, t) for x, t in zip(obj, type_args)]
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/registry_utils.py", line 78, in wrapper
    return base_func(*args, **kw)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 118, in encode
    raise e
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/draccus/parsers/encoding.py", line 115, in encode
    raise Exception(f"No parser for object {obj} of type {type(obj)}, consider using draccus.encode.register")
Exception: No parser for object download/llava-laion-cc-sbu-558k/chat.json of type <class 'pathlib.PosixPath'>, consider using draccus.encode.register
[2025-04-30 12:31:17,129] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 97282) of binary: /home/user1/anaconda3/envs/prism/bin/python
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/prism/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user1/anaconda3/envs/prism/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/pretrain.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-04-30_12:31:17
  host      : nnmc71
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 97282)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
